language: rust
sudo: true
dist: xenial

install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get -y update
  - sudo apt-get -y install gcc-arm-embedded
  - rustup target add armv7r-none-eabi

cache: 
  - apt
  - cargo

rust:
- stable

script:
  - cargo build
  - make all
